import fs from 'fs';
import path from 'path';
import {
  supabaseService,
  DEFAULT_SUPABASE_URL,
  DEFAULT_SUPABASE_ANON_KEY,
  DEFAULT_SUPABASE_SERVICE_ROLE_KEY,
  DEFAULT_PROJECT_REF,
  DEFAULT_DB_URL,
} from './supabase';
import {
  User,
  Customer,
  DeliveryBoy,
  Auditor,
  Product,
  ProductBatch,
  PurchaseEntry,
  Order,
  PantryCardItem,
  PantryCreditLedger,
  WalletTransaction,
  ReturnRequest,
  ReplacementRequest,
  AuditorCheck,
  AuditorReturnOrder,
  InventoryTransaction,
  AuditLog,
  AppSettings,
  DashboardSummary,
  PantryPayment,
  WalletRechargeRequest,
} from '../src/types';

interface DatabaseSchema {
  users: User[];
  customers: Customer[];
  deliveryBoys: DeliveryBoy[];
  auditors: Auditor[];
  products: Product[];
  batches: ProductBatch[];
  purchases: PurchaseEntry[];
  orders: Order[];
  pantryCardItems: PantryCardItem[];
  pantryCreditLedger: PantryCreditLedger[];
  walletTransactions: WalletTransaction[];
  walletRechargeRequests?: WalletRechargeRequest[];
  returnRequests: ReturnRequest[];
  replacementRequests: ReplacementRequest[];
  auditorChecks: AuditorCheck[];
  inventoryTransactions: InventoryTransaction[];
  auditLogs: AuditLog[];
  settings: AppSettings;
  pantryPayments: PantryPayment[];
  auditorReturnOrders?: AuditorReturnOrder[];
}

const DATA_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DATA_DIR, 'db.json');

// Helper to format ISO dates
const today = new Date().toISOString().split('T')[0];
const daysAgo = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
};
const daysFuture = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

const getInitialSeeds = (): DatabaseSchema => {
  const defaultSettings: AppSettings = {
    defaultPantryLimit: 10000,
    defaultWalletBalance: 1000,
    walletRechargeEnabled: true,
    auditWalletDeductionEnabled: true,
    allowNegativeWallet: false,
    auditRequireCustomerConfirmation: true,
    pantryReturnWindowDays: 15,
    nearExpiryDays: 30,
    lowStockThreshold: 5,
    codEnabled: true,
    pantryOrderCodEnabled: false,
    autoAssignDelivery: false,
    allowChildAccounts: true,
    maxChildAccountsPerCustomer: 3,
    activeThemeId: 'yellow-amber',
    apiIntegrations: {
      payment: {
        mode: 'DEMO',
        provider: 'RAZORPAY',
        enabled: true,
        apiKeyId: 'rzp_test_demo1234567890',
        apiSecret: 'demo_secret_key_89012345',
        merchantId: 'MERCHANT_DEMO_01',
        webhookSecret: 'whsec_demo_hash_key',
        autoCapture: true,
        currency: 'INR',
        lastTestedAt: new Date().toISOString(),
        lastTestStatus: 'SUCCESS',
        lastTestMessage: 'Demo UPI / Razorpay Gateway Simulator Ready',
      },
      sms: {
        mode: 'DEMO',
        provider: 'MSG91',
        enabled: true,
        apiKey: 'demo_msg91_auth_key_123456',
        senderId: 'PNTRYM',
        dltEntityId: '1301159876543210',
        otpTemplateId: '1307161234567890',
        orderDispatchTemplateId: '1307161234567891',
        lastTestedAt: new Date().toISOString(),
        lastTestStatus: 'SUCCESS',
        lastTestMessage: 'In-Memory Demo SMS Gateway Active',
      },
      whatsApp: {
        mode: 'DEMO',
        provider: 'META_WHATSAPP',
        enabled: true,
        accessToken: 'EAAG_demo_meta_whatsapp_access_token',
        phoneNumberId: '109876543210123',
        businessAccountId: '209876543210123',
        defaultTemplateName: 'order_receipt_notification',
        lastTestedAt: new Date().toISOString(),
        lastTestStatus: 'SUCCESS',
        lastTestMessage: 'Console Logger WhatsApp Business Simulator Active',
      },
      googleMaps: {
        mode: 'DEMO',
        provider: 'GOOGLE_MAPS',
        enabled: true,
        apiKey: 'AIzaSyDemoGoogleMapsApiKey_1234567890',
        enableGeocoding: true,
        enablePlacesAutocomplete: true,
        enableStaticMaps: true,
        lastTestedAt: new Date().toISOString(),
        lastTestStatus: 'SUCCESS',
        lastTestMessage: 'Mock Geocoder & Map Renderer Ready',
      },
      aiGemini: {
        mode: 'DEMO',
        provider: 'GOOGLE_GEMINI',
        enabled: true,
        apiKey: process.env.GEMINI_API_KEY || 'demo_gemini_api_key_12345',
        preferredModel: 'gemini-2.5-flash',
        enableSmartAssistant: true,
        lastTestedAt: new Date().toISOString(),
        lastTestStatus: 'SUCCESS',
        lastTestMessage: 'Google Gemini 2.5 Flash Engine Connected',
      },
      cloudStorage: {
        mode: 'DEMO',
        provider: 'AWS_S3',
        enabled: true,
        bucketName: 'pantrymaster-app-storage',
        region: 'ap-south-1',
        accessKeyId: 'AKIA_DEMO_ACCESS_KEY',
        secretAccessKey: 'demo_secret_storage_key_98765',
        cdnBaseUrl: 'https://cdn.pantrymaster.app',
        lastTestedAt: new Date().toISOString(),
        lastTestStatus: 'SUCCESS',
        lastTestMessage: 'Local Storage / Mock Asset Server Active',
      },
      supabase: {
        mode: 'LIVE',
        provider: 'SUPABASE',
        enabled: true,
        url: DEFAULT_SUPABASE_URL,
        anonKey: DEFAULT_SUPABASE_ANON_KEY,
        projectRef: DEFAULT_PROJECT_REF,
        dbUrl: DEFAULT_DB_URL,
        autoSync: true,
        lastTestedAt: new Date().toISOString(),
        lastTestStatus: 'SUCCESS',
        lastTestMessage: 'Supabase Cloud Database (bgxnmmecjcgrwtemmjtz) connected',
        connected: true,
      },
    },
  };

  const users: User[] = [
    {
      id: 'USR-ADMIN-01',
      mobile: '9876543210',
      name: 'System Administrator',
      role: 'ADMIN',
      status: 'ACTIVE',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(30),
    },
    {
      id: 'USR-CUS-01',
      mobile: '9123456780',
      name: 'Ramesh Kumar (Parent)',
      role: 'CUSTOMER',
      customerId: 'CUS-000001',
      status: 'ACTIVE',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(20),
    },
    {
      id: 'USR-CUS-02',
      mobile: '9123456781',
      name: 'Sunita Kumar (Child)',
      role: 'CUSTOMER',
      customerId: 'CUS-000001-01',
      status: 'ACTIVE',
      createdAt: daysAgo(15),
      updatedAt: daysAgo(15),
    },
    {
      id: 'USR-CUS-03',
      mobile: '9835012345',
      name: 'Priya Sharma',
      role: 'CUSTOMER',
      customerId: 'CUS-000002',
      status: 'ACTIVE',
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
    },
    {
      id: 'USR-CUS-04',
      mobile: '9431198765',
      name: 'Amit Verma',
      role: 'CUSTOMER',
      customerId: 'CUS-000003',
      status: 'ACTIVE',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
    {
      id: 'USR-DEL-01',
      mobile: '9988776655',
      name: 'Rajesh Delivery Boy',
      role: 'DELIVERY_BOY',
      deliveryBoyId: 'DEL-001',
      status: 'ACTIVE',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(25),
    },
    {
      id: 'USR-DEL-02',
      mobile: '9988776656',
      name: 'Vikram Singh (Rider)',
      role: 'DELIVERY_BOY',
      deliveryBoyId: 'DEL-002',
      status: 'ACTIVE',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(20),
    },
    {
      id: 'USR-DEL-03',
      mobile: '9988776657',
      name: 'Manoj Kumar',
      role: 'DELIVERY_BOY',
      deliveryBoyId: 'DEL-003',
      status: 'ACTIVE',
      createdAt: daysAgo(18),
      updatedAt: daysAgo(18),
    },
    {
      id: 'USR-AUD-01',
      mobile: '9876500001',
      name: 'Suresh Field Auditor',
      role: 'AUDITOR',
      auditorId: 'AUD-001',
      status: 'ACTIVE',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(25),
    },
    {
      id: 'USR-AUD-02',
      mobile: '9876500002',
      name: 'Anjali Verma (Senior Auditor)',
      role: 'AUDITOR',
      auditorId: 'AUD-002',
      status: 'ACTIVE',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(20),
    },
  ];

  const customers: Customer[] = [
    {
      id: 'CUS-000001',
      fullName: 'Ramesh Kumar',
      mobile: '9123456780',
      alternateMobile: '9835000000',
      address: 'Flat 402, Shanti Vihar, Circular Road',
      area: 'Lalpur',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834001',
      landmark: 'Near Women\'s College',
      relationInfo: 'Self / Head of Family',
      isChild: false,
      childCustomerIds: ['CUS-000001-01', 'CUS-000001-02'],
      pantryLimit: 10000,
      usedPantryLimit: 2450,
      availablePantryLimit: 7550,
      walletBalance: 1000,
      status: 'ACTIVE',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(1),
    },
    {
      id: 'CUS-000001-01',
      fullName: 'Sunita Kumar',
      mobile: '9123456781',
      address: 'Flat 402, Shanti Vihar, Circular Road',
      area: 'Lalpur',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834001',
      landmark: 'Near Women\'s College',
      relationInfo: 'Spouse',
      isChild: true,
      parentCustomerId: 'CUS-000001',
      childCustomerIds: [],
      pantryLimit: 5000,
      usedPantryLimit: 850,
      availablePantryLimit: 4150,
      walletBalance: 1000,
      status: 'ACTIVE',
      createdAt: daysAgo(15),
      updatedAt: daysAgo(2),
    },
    {
      id: 'CUS-000001-02',
      fullName: 'Rohit Kumar',
      mobile: '9123456782',
      address: 'Hostel 3, BIT Mesra Campus',
      area: 'Mesra',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '835215',
      relationInfo: 'Son',
      isChild: true,
      parentCustomerId: 'CUS-000001',
      childCustomerIds: [],
      pantryLimit: 3000,
      usedPantryLimit: 0,
      availablePantryLimit: 3000,
      walletBalance: 1000,
      status: 'ACTIVE',
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
    },
    {
      id: 'CUS-000002',
      fullName: 'Priya Sharma',
      mobile: '9835012345',
      alternateMobile: '9431100000',
      address: 'House No 12, Harmu Housing Colony',
      area: 'Harmu',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834002',
      landmark: 'Opposite Ground',
      relationInfo: 'Self',
      isChild: false,
      childCustomerIds: [],
      pantryLimit: 15000,
      usedPantryLimit: 4200,
      availablePantryLimit: 10800,
      walletBalance: 2000,
      status: 'ACTIVE',
      createdAt: daysAgo(10),
      updatedAt: daysAgo(3),
    },
    {
      id: 'CUS-000003',
      fullName: 'Amit Verma',
      mobile: '9431198765',
      address: 'Plot 88, Ashok Nagar, Road No 4',
      area: 'Ashok Nagar',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834002',
      landmark: 'Near Gate 2',
      relationInfo: 'Self',
      isChild: false,
      childCustomerIds: [],
      pantryLimit: 7500,
      usedPantryLimit: 0,
      availablePantryLimit: 7500,
      walletBalance: 1000,
      status: 'ACTIVE',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
  ];

  const deliveryBoys: DeliveryBoy[] = [
    {
      id: 'DEL-001',
      fullName: 'Rajesh Delivery Boy',
      mobile: '9988776655',
      alternateContact: '9876543001',
      address: 'Kanke Road, Near CM House',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834008',
      assignedArea: 'Lalpur & Main Road',
      vehicleType: 'BIKE',
      vehicleNumber: 'JH01-BX-4321',
      joiningDate: daysAgo(40),
      status: 'ACTIVE',
      notes: 'Reliable and punctual rider',
    },
    {
      id: 'DEL-002',
      fullName: 'Vikram Singh',
      mobile: '9988776656',
      address: 'Doranda Bazar, High Court Area',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834002',
      assignedArea: 'Harmu & Ashok Nagar',
      vehicleType: 'SCOOTER',
      vehicleNumber: 'JH01-CY-8899',
      joiningDate: daysAgo(30),
      status: 'ACTIVE',
    },
    {
      id: 'DEL-003',
      fullName: 'Manoj Kumar',
      mobile: '9988776657',
      address: 'Ratu Road, Pandra Market',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834005',
      assignedArea: 'Ratu Road & Bariatu',
      vehicleType: 'VAN',
      vehicleNumber: 'JH01-E-1200',
      joiningDate: daysAgo(20),
      status: 'ACTIVE',
    },
  ];

  const auditors: Auditor[] = [
    {
      id: 'AUD-001',
      fullName: 'Suresh Field Auditor',
      mobile: '9876500001',
      email: 'suresh.auditor@pantrymart.com',
      assignedZone: 'Central Ranchi (Zone A)',
      assignedCustomerIds: ['CUS-000001', 'CUS-000001-01', 'CUS-000001-02'],
      joiningDate: daysAgo(45),
      status: 'ACTIVE',
      totalChecksConducted: 14,
    },
    {
      id: 'AUD-002',
      fullName: 'Anjali Verma',
      mobile: '9876500002',
      email: 'anjali.auditor@pantrymart.com',
      assignedZone: 'South Ranchi (Zone B)',
      assignedCustomerIds: ['CUS-000002'],
      joiningDate: daysAgo(30),
      status: 'ACTIVE',
      totalChecksConducted: 8,
    },
  ];

  const products: Product[] = [
    {
      id: 'PRD-001',
      name: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      brand: 'Horlicks',
      category: 'Beverages & Health Drinks',
      subCategory: 'Health Drinks',
      unit: 'packet',
      weightSize: '500g',
      description: 'Clinically proven malted drink that nourishes the body with 23 vital nutrients.',
      hsn: '19011090',
      barcode: '123456789',
      mrp: 320,
      sellingPrice: 285,
      discount: 11,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(30),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-002',
      name: 'Aashirvaad Superior MP Shudh Chakki Atta 5kg',
      brand: 'Aashirvaad',
      category: 'Atta, Flours & Grains',
      subCategory: 'Wheat Atta',
      unit: 'bag',
      weightSize: '5kg',
      description: '100% pure whole wheat grain flour with authentic chakki grinding method.',
      hsn: '11010000',
      barcode: '8901030382910',
      mrp: 295,
      sellingPrice: 265,
      discount: 10,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(28),
      updatedAt: daysAgo(2),
    },
    {
      id: 'PRD-003',
      name: 'Fortune Sunlite Refined Sunflower Oil 1L Pouch',
      brand: 'Fortune',
      category: 'Edible Oils & Ghee',
      subCategory: 'Refined Oil',
      unit: 'pouch',
      weightSize: '1L',
      description: 'Light, healthy and cholesterol friendly cooking oil enriched with vitamins A & D.',
      hsn: '15121910',
      barcode: '8906007281023',
      mrp: 175,
      sellingPrice: 152,
      discount: 13,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(28),
      updatedAt: daysAgo(2),
    },
    {
      id: 'PRD-004',
      name: 'India Gate Basmati Rice Premium Feast Rozzana 1kg',
      brand: 'India Gate',
      category: 'Rice & Rice Products',
      subCategory: 'Basmati Rice',
      unit: 'bag',
      weightSize: '1kg',
      description: 'Aromatic, slender long-grain aged basmati rice for daily delicacies.',
      hsn: '10063020',
      barcode: '8901725114221',
      mrp: 140,
      sellingPrice: 118,
      discount: 15,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-005',
      name: 'Tata Salt Vacuum Evaporated Iodized Salt 1kg',
      brand: 'Tata',
      category: 'Salt, Sugar & Jaggery',
      subCategory: 'Table Salt',
      unit: 'packet',
      weightSize: '1kg',
      description: 'Desh Ka Namak with guaranteed iodine purity and vacuum evaporation.',
      hsn: '25010010',
      barcode: '8901058852303',
      mrp: 30,
      sellingPrice: 28,
      discount: 6,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-006',
      name: 'Tata Sampann Unpolished Toor Dal Arhar Dal 1kg',
      brand: 'Tata Sampann',
      category: 'Dals & Pulses',
      subCategory: 'Toor Dal',
      unit: 'packet',
      weightSize: '1kg',
      description: 'High protein unpolished toor dal retaining wholesome natural nutrition.',
      hsn: '07136000',
      barcode: '8901058852990',
      mrp: 195,
      sellingPrice: 172,
      discount: 12,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1585994276707-1b09b55589c3?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(22),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-007',
      name: 'Maggi 2-Minute Masala Instant Noodles 420g (Pack of 6)',
      brand: 'Nestle Maggi',
      category: 'Instant Food & Noodles',
      subCategory: 'Noodles',
      unit: 'pack',
      weightSize: '420g',
      description: 'Iconic spicy instant noodles prepared in 2 minutes with authentic tastemaker.',
      hsn: '19023010',
      barcode: '8901058847101',
      mrp: 96,
      sellingPrice: 88,
      discount: 8,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(20),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-008',
      name: 'Britannia Good Day Cashew Cookies 600g Value Pack',
      brand: 'Britannia',
      category: 'Snacks & Biscuits',
      subCategory: 'Cookies',
      unit: 'pack',
      weightSize: '600g',
      description: 'Rich buttery crunchy cookies loaded with wholesome cashew nuts.',
      hsn: '19053100',
      barcode: '8901063012019',
      mrp: 140,
      sellingPrice: 125,
      discount: 10,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(18),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-009',
      name: 'Surf Excel Quick Wash Detergent Powder 1kg',
      brand: 'Surf Excel',
      category: 'Cleaning & Household',
      subCategory: 'Laundry Detergents',
      unit: 'packet',
      weightSize: '1kg',
      description: 'Superfast stain removal powder suitable for bucket & machine wash.',
      hsn: '34029011',
      barcode: '8901030704989',
      mrp: 160,
      sellingPrice: 145,
      discount: 9,
      orderEligibility: 'PANTRY_ONLY',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1585994276707-1b09b55589c3?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(18),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-010',
      name: 'Dettol Original Germ Protection Bathing Soap Bar (Pack of 4 x 125g)',
      brand: 'Dettol',
      category: 'Personal Care & Hygiene',
      subCategory: 'Soaps',
      unit: 'pack',
      weightSize: '500g',
      description: 'Trusted 99.9% germ protection soap bar infused with classic pine fragrance.',
      hsn: '34011110',
      barcode: '8901396128001',
      mrp: 210,
      sellingPrice: 185,
      discount: 12,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1607006310414-b58602b9d628?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(15),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-011',
      name: 'Amul Pure Ghee 1L Tin',
      brand: 'Amul',
      category: 'Edible Oils & Ghee',
      subCategory: 'Desi Ghee',
      unit: 'tin',
      weightSize: '1L',
      description: 'Aromatic pure cow & buffalo milk ghee with rich granular texture.',
      hsn: '04059020',
      barcode: '8901262010111',
      mrp: 650,
      sellingPrice: 595,
      discount: 8,
      orderEligibility: 'BOTH',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(14),
      updatedAt: daysAgo(1),
    },
    {
      id: 'PRD-012',
      name: 'Fresh Harvest Daily Whole Wheat Bread 400g (Near Expiry Sample)',
      brand: 'FreshBake',
      category: 'Bakery & Bread',
      subCategory: 'Breads',
      unit: 'packet',
      weightSize: '400g',
      description: 'Soft whole wheat daily breakfast bread baked fresh with natural ingredients.',
      hsn: '19059010',
      barcode: '8909991234567',
      mrp: 50,
      sellingPrice: 42,
      discount: 16,
      orderEligibility: 'QUICK_ONLY',
      status: 'PUBLISHED',
      images: [
        'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=600&q=80',
      ],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(1),
    },
  ];

  // Batches: Explicit product + batch with mandatory Shopkeeper Name
  const batches: ProductBatch[] = [
    // Horlicks: Batch 124001 (Stock added: 5 + 3 = 8, 2 sold to Pantry, 1 sold to Quick, 1 returned -> 6 available)
    {
      id: 'BATCH-001',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      barcode: '123456789',
      batchNumber: '124001',
      manufacturingDate: daysAgo(60),
      expiryDate: daysFuture(300),
      purchaseQuantity: 8,
      availableQuantity: 6,
      reservedQuantity: 0,
      quickSoldQuantity: 1,
      pantrySoldQuantity: 2,
      returnedQuantity: 1,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      shopkeeperContact: '9835123400',
      purchaseRate: 240,
      mrp: 320,
      sellingPrice: 285,
      createdAt: daysAgo(30),
      updatedAt: daysAgo(1),
    },
    // Horlicks: Batch 124002 (Separate batch with 10 units)
    {
      id: 'BATCH-002',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      barcode: '123456789',
      batchNumber: '124002',
      manufacturingDate: daysAgo(30),
      expiryDate: daysFuture(360),
      purchaseQuantity: 10,
      availableQuantity: 10,
      reservedQuantity: 0,
      quickSoldQuantity: 0,
      pantrySoldQuantity: 0,
      returnedQuantity: 0,
      shopkeeperName: 'Gupta Agro Suppliers Pvt Ltd',
      shopkeeperContact: '9431188776',
      purchaseRate: 242,
      mrp: 320,
      sellingPrice: 285,
      createdAt: daysAgo(15),
      updatedAt: daysAgo(15),
    },
    // Atta: Batch ATT-801
    {
      id: 'BATCH-003',
      productId: 'PRD-002',
      productName: 'Aashirvaad Superior MP Shudh Chakki Atta 5kg',
      barcode: '8901030382910',
      batchNumber: 'ATT-801',
      manufacturingDate: daysAgo(25),
      expiryDate: daysFuture(155),
      purchaseQuantity: 25,
      availableQuantity: 21,
      reservedQuantity: 0,
      quickSoldQuantity: 2,
      pantrySoldQuantity: 2,
      returnedQuantity: 0,
      shopkeeperName: 'Jharkhand Grain Distributors',
      shopkeeperContact: '9835099887',
      purchaseRate: 225,
      mrp: 295,
      sellingPrice: 265,
      createdAt: daysAgo(25),
      updatedAt: daysAgo(2),
    },
    // Sunflower Oil: Batch OIL-502
    {
      id: 'BATCH-004',
      productId: 'PRD-003',
      productName: 'Fortune Sunlite Refined Sunflower Oil 1L Pouch',
      barcode: '8906007281023',
      batchNumber: 'OIL-502',
      manufacturingDate: daysAgo(40),
      expiryDate: daysFuture(200),
      purchaseQuantity: 30,
      availableQuantity: 26,
      reservedQuantity: 0,
      quickSoldQuantity: 2,
      pantrySoldQuantity: 2,
      returnedQuantity: 0,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      shopkeeperContact: '9835123400',
      purchaseRate: 130,
      mrp: 175,
      sellingPrice: 152,
      createdAt: daysAgo(28),
      updatedAt: daysAgo(2),
    },
    // Basmati Rice: Batch RICE-99
    {
      id: 'BATCH-005',
      productId: 'PRD-004',
      productName: 'India Gate Basmati Rice Premium Feast Rozzana 1kg',
      barcode: '8901725114221',
      batchNumber: 'RICE-99',
      manufacturingDate: daysAgo(90),
      expiryDate: daysFuture(400),
      purchaseQuantity: 40,
      availableQuantity: 38,
      reservedQuantity: 0,
      quickSoldQuantity: 1,
      pantrySoldQuantity: 1,
      returnedQuantity: 0,
      shopkeeperName: 'Gupta Agro Suppliers Pvt Ltd',
      purchaseRate: 95,
      mrp: 140,
      sellingPrice: 118,
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    // Tata Salt: Batch SLT-11
    {
      id: 'BATCH-006',
      productId: 'PRD-005',
      productName: 'Tata Salt Vacuum Evaporated Iodized Salt 1kg',
      barcode: '8901058852303',
      batchNumber: 'SLT-11',
      manufacturingDate: daysAgo(45),
      expiryDate: daysFuture(600),
      purchaseQuantity: 50,
      availableQuantity: 46,
      reservedQuantity: 0,
      quickSoldQuantity: 2,
      pantrySoldQuantity: 2,
      returnedQuantity: 0,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      purchaseRate: 21,
      mrp: 30,
      sellingPrice: 28,
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    // Toor Dal: Batch DAL-44
    {
      id: 'BATCH-007',
      productId: 'PRD-006',
      productName: 'Tata Sampann Unpolished Toor Dal Arhar Dal 1kg',
      barcode: '8901058852990',
      batchNumber: 'DAL-44',
      manufacturingDate: daysAgo(30),
      expiryDate: daysFuture(330),
      purchaseQuantity: 20,
      availableQuantity: 18,
      reservedQuantity: 0,
      quickSoldQuantity: 1,
      pantrySoldQuantity: 1,
      returnedQuantity: 0,
      shopkeeperName: 'Jharkhand Grain Distributors',
      purchaseRate: 148,
      mrp: 195,
      sellingPrice: 172,
      createdAt: daysAgo(22),
      updatedAt: daysAgo(1),
    },
    // Maggi: Batch MAG-707
    {
      id: 'BATCH-008',
      productId: 'PRD-007',
      productName: 'Maggi 2-Minute Masala Instant Noodles 420g (Pack of 6)',
      barcode: '8901058847101',
      batchNumber: 'MAG-707',
      manufacturingDate: daysAgo(20),
      expiryDate: daysFuture(240),
      purchaseQuantity: 30,
      availableQuantity: 27,
      reservedQuantity: 0,
      quickSoldQuantity: 2,
      pantrySoldQuantity: 1,
      returnedQuantity: 0,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      purchaseRate: 74,
      mrp: 96,
      sellingPrice: 88,
      createdAt: daysAgo(20),
      updatedAt: daysAgo(1),
    },
    // Britannia Good Day: Batch GDAY-301
    {
      id: 'BATCH-009',
      productId: 'PRD-008',
      productName: 'Britannia Good Day Cashew Cookies 600g Value Pack',
      barcode: '8901063012019',
      batchNumber: 'GDAY-301',
      manufacturingDate: daysAgo(25),
      expiryDate: daysFuture(150),
      purchaseQuantity: 25,
      availableQuantity: 22,
      reservedQuantity: 0,
      quickSoldQuantity: 2,
      pantrySoldQuantity: 1,
      returnedQuantity: 0,
      shopkeeperName: 'Gupta Agro Suppliers Pvt Ltd',
      purchaseRate: 102,
      mrp: 140,
      sellingPrice: 125,
      createdAt: daysAgo(18),
      updatedAt: daysAgo(1),
    },
    // Surf Excel: Batch SRF-201
    {
      id: 'BATCH-010',
      productId: 'PRD-009',
      productName: 'Surf Excel Quick Wash Detergent Powder 1kg',
      barcode: '8901030704989',
      batchNumber: 'SRF-201',
      manufacturingDate: daysAgo(40),
      expiryDate: daysFuture(500),
      purchaseQuantity: 20,
      availableQuantity: 18,
      reservedQuantity: 0,
      quickSoldQuantity: 0,
      pantrySoldQuantity: 2,
      returnedQuantity: 0,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      purchaseRate: 120,
      mrp: 160,
      sellingPrice: 145,
      createdAt: daysAgo(18),
      updatedAt: daysAgo(1),
    },
    // Dettol Soap: Batch DET-909
    {
      id: 'BATCH-011',
      productId: 'PRD-010',
      productName: 'Dettol Original Germ Protection Bathing Soap Bar (Pack of 4 x 125g)',
      barcode: '8901396128001',
      batchNumber: 'DET-909',
      manufacturingDate: daysAgo(50),
      expiryDate: daysFuture(600),
      purchaseQuantity: 25,
      availableQuantity: 23,
      reservedQuantity: 0,
      quickSoldQuantity: 1,
      pantrySoldQuantity: 1,
      returnedQuantity: 0,
      shopkeeperName: 'Gupta Agro Suppliers Pvt Ltd',
      purchaseRate: 155,
      mrp: 210,
      sellingPrice: 185,
      createdAt: daysAgo(15),
      updatedAt: daysAgo(1),
    },
    // Near Expiry Batch Sample (Fresh Bread: expiring in 8 days)
    {
      id: 'BATCH-012',
      productId: 'PRD-012',
      productName: 'Fresh Harvest Daily Whole Wheat Bread 400g (Near Expiry Sample)',
      barcode: '8909991234567',
      batchNumber: 'BRD-NEX-01',
      manufacturingDate: daysAgo(4),
      expiryDate: daysFuture(8), // Within 30 days -> Near Expiry
      purchaseQuantity: 15,
      availableQuantity: 12,
      reservedQuantity: 0,
      quickSoldQuantity: 3,
      pantrySoldQuantity: 0,
      returnedQuantity: 0,
      shopkeeperName: 'BakeWell Foods Ranchi',
      purchaseRate: 30,
      mrp: 50,
      sellingPrice: 42,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(1),
    },
    // Expired Batch Sample for verification
    {
      id: 'BATCH-013',
      productId: 'PRD-012',
      productName: 'Fresh Harvest Daily Whole Wheat Bread 400g (Near Expiry Sample)',
      barcode: '8909991234567',
      batchNumber: 'BRD-EXP-OLD',
      manufacturingDate: daysAgo(45),
      expiryDate: daysAgo(5), // Already Expired
      purchaseQuantity: 10,
      availableQuantity: 4,
      reservedQuantity: 0,
      quickSoldQuantity: 6,
      pantrySoldQuantity: 0,
      returnedQuantity: 0,
      shopkeeperName: 'BakeWell Foods Ranchi',
      purchaseRate: 30,
      mrp: 50,
      sellingPrice: 42,
      createdAt: daysAgo(45),
      updatedAt: daysAgo(5),
    },
  ];

  // Purchases
  const purchases: PurchaseEntry[] = [
    {
      id: 'PUR-001',
      purchaseDate: daysAgo(30),
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      barcode: '123456789',
      batchNumber: '124001',
      manufacturingDate: daysAgo(60),
      expiryDate: daysFuture(300),
      quantity: 5,
      purchaseRate: 240,
      mrp: 320,
      sellingPrice: 285,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      shopkeeperContact: '9835123400',
      invoiceReference: 'INV-2026-9081',
      notes: 'Initial lot of 5 packets received',
      createdAt: daysAgo(30),
    },
    {
      id: 'PUR-002',
      purchaseDate: daysAgo(28),
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      barcode: '123456789',
      batchNumber: '124001', // Same batch quantity addition (+3 -> total 8)
      manufacturingDate: daysAgo(60),
      expiryDate: daysFuture(300),
      quantity: 3,
      purchaseRate: 240,
      mrp: 320,
      sellingPrice: 285,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      shopkeeperContact: '9835123400',
      invoiceReference: 'INV-2026-9140',
      notes: 'Repeat stock-in of batch 124001 (+3 packets)',
      createdAt: daysAgo(28),
    },
    {
      id: 'PUR-003',
      purchaseDate: daysAgo(15),
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      barcode: '123456789',
      batchNumber: '124002', // Different batch
      manufacturingDate: daysAgo(30),
      expiryDate: daysFuture(360),
      quantity: 10,
      purchaseRate: 242,
      mrp: 320,
      sellingPrice: 285,
      shopkeeperName: 'Gupta Agro Suppliers Pvt Ltd',
      shopkeeperContact: '9431188776',
      invoiceReference: 'GAS-RNC-441',
      notes: 'New manufacturing batch 124002',
      createdAt: daysAgo(15),
    },
    {
      id: 'PUR-004',
      purchaseDate: daysAgo(25),
      productId: 'PRD-002',
      productName: 'Aashirvaad Superior MP Shudh Chakki Atta 5kg',
      barcode: '8901030382910',
      batchNumber: 'ATT-801',
      manufacturingDate: daysAgo(25),
      expiryDate: daysFuture(155),
      quantity: 25,
      purchaseRate: 225,
      mrp: 295,
      sellingPrice: 265,
      shopkeeperName: 'Jharkhand Grain Distributors',
      shopkeeperContact: '9835099887',
      invoiceReference: 'JGD-1022',
      createdAt: daysAgo(25),
    },
    {
      id: 'PUR-005',
      purchaseDate: daysAgo(28),
      productId: 'PRD-003',
      productName: 'Fortune Sunlite Refined Sunflower Oil 1L Pouch',
      barcode: '8906007281023',
      batchNumber: 'OIL-502',
      manufacturingDate: daysAgo(40),
      expiryDate: daysFuture(200),
      quantity: 30,
      purchaseRate: 130,
      mrp: 175,
      sellingPrice: 152,
      shopkeeperName: 'Ranchi Wholesale FMCG Mart',
      invoiceReference: 'INV-2026-9099',
      createdAt: daysAgo(28),
    },
  ];

  // Orders
  const orders: Order[] = [
    // Pantry Order delivered to Ramesh Kumar 9 days ago
    {
      id: 'ORD-P-1001',
      orderType: 'PANTRY',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      customerMobile: '9123456780',
      deliveryAddress: 'Flat 402, Shanti Vihar, Circular Road, Lalpur, Ranchi - 834001',
      items: [
        {
          productId: 'PRD-001',
          productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
          brand: 'Horlicks',
          weightSize: '500g',
          barcode: '123456789',
          batchId: 'BATCH-001',
          batchNumber: '124001',
          manufacturingDate: daysAgo(60),
          expiryDate: daysFuture(300),
          quantity: 2,
          price: 285,
          mrp: 320,
          image: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
        },
        {
          productId: 'PRD-002',
          productName: 'Aashirvaad Superior MP Shudh Chakki Atta 5kg',
          brand: 'Aashirvaad',
          weightSize: '5kg',
          barcode: '8901030382910',
          batchId: 'BATCH-003',
          batchNumber: 'ATT-801',
          manufacturingDate: daysAgo(25),
          expiryDate: daysFuture(155),
          quantity: 1,
          price: 265,
          mrp: 295,
          image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        },
        {
          productId: 'PRD-003',
          productName: 'Fortune Sunlite Refined Sunflower Oil 1L Pouch',
          brand: 'Fortune',
          weightSize: '1L',
          barcode: '8906007281023',
          batchId: 'BATCH-004',
          batchNumber: 'OIL-502',
          manufacturingDate: daysAgo(40),
          expiryDate: daysFuture(200),
          quantity: 1,
          price: 152,
          mrp: 175,
          image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 987,
      deliveryFee: 0,
      totalAmount: 987,
      pantryDebitAmount: 987,
      codAmount: 0,
      paymentStatus: 'PANTRY_CREDIT_DEBITED',
      orderStatus: 'DELIVERED',
      assignedDeliveryBoyId: 'DEL-001',
      assignedDeliveryBoyName: 'Rajesh Delivery Boy',
      assignedDeliveryBoyMobile: '9988776655',
      assignedAt: daysAgo(10),
      deliveredAt: daysAgo(9),
      createdAt: daysAgo(10),
      updatedAt: daysAgo(9),
    },
    // Quick Order delivered to Ramesh Kumar (COD) 3 days ago
    {
      id: 'ORD-Q-2001',
      orderType: 'QUICK',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      customerMobile: '9123456780',
      deliveryAddress: 'Flat 402, Shanti Vihar, Circular Road, Lalpur, Ranchi - 834001',
      items: [
        {
          productId: 'PRD-007',
          productName: 'Maggi 2-Minute Masala Instant Noodles 420g (Pack of 6)',
          brand: 'Nestle Maggi',
          weightSize: '420g',
          barcode: '8901058847101',
          batchId: 'BATCH-008',
          batchNumber: 'MAG-707',
          manufacturingDate: daysAgo(20),
          expiryDate: daysFuture(240),
          quantity: 2,
          price: 88,
          mrp: 96,
          image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
        },
        {
          productId: 'PRD-008',
          productName: 'Britannia Good Day Cashew Cookies 600g Value Pack',
          brand: 'Britannia',
          weightSize: '600g',
          barcode: '8901063012019',
          batchId: 'BATCH-009',
          batchNumber: 'GDAY-301',
          manufacturingDate: daysAgo(25),
          expiryDate: daysFuture(150),
          quantity: 1,
          price: 125,
          mrp: 140,
          image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 301,
      deliveryFee: 20,
      totalAmount: 321,
      pantryDebitAmount: 0,
      codAmount: 321,
      paymentStatus: 'COD_COLLECTED',
      orderStatus: 'DELIVERED',
      assignedDeliveryBoyId: 'DEL-001',
      assignedDeliveryBoyName: 'Rajesh Delivery Boy',
      assignedDeliveryBoyMobile: '9988776655',
      assignedAt: daysAgo(4),
      deliveredAt: daysAgo(3),
      codCollectedAt: daysAgo(3),
      createdAt: daysAgo(4),
      updatedAt: daysAgo(3),
    },
    // Pantry Order for Sunita Kumar (Child) delivered 5 days ago
    {
      id: 'ORD-P-1002',
      orderType: 'PANTRY',
      customerId: 'CUS-000001-01',
      customerName: 'Sunita Kumar',
      customerMobile: '9123456781',
      deliveryAddress: 'Flat 402, Shanti Vihar, Circular Road, Lalpur, Ranchi - 834001',
      items: [
        {
          productId: 'PRD-009',
          productName: 'Surf Excel Quick Wash Detergent Powder 1kg',
          brand: 'Surf Excel',
          weightSize: '1kg',
          barcode: '8901030704989',
          batchId: 'BATCH-010',
          batchNumber: 'SRF-201',
          manufacturingDate: daysAgo(40),
          expiryDate: daysFuture(500),
          quantity: 2,
          price: 145,
          mrp: 160,
          image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
        },
        {
          productId: 'PRD-010',
          productName: 'Dettol Original Germ Protection Bathing Soap Bar (Pack of 4 x 125g)',
          brand: 'Dettol',
          weightSize: '500g',
          barcode: '8901396128001',
          batchId: 'BATCH-011',
          batchNumber: 'DET-909',
          manufacturingDate: daysAgo(50),
          expiryDate: daysFuture(600),
          quantity: 1,
          price: 185,
          mrp: 210,
          image: 'https://images.unsplash.com/photo-1607006310414-b58602b9d628?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 475,
      deliveryFee: 0,
      totalAmount: 475,
      pantryDebitAmount: 475,
      codAmount: 0,
      paymentStatus: 'PANTRY_CREDIT_DEBITED',
      orderStatus: 'DELIVERED',
      assignedDeliveryBoyId: 'DEL-001',
      assignedDeliveryBoyName: 'Rajesh Delivery Boy',
      assignedAt: daysAgo(6),
      deliveredAt: daysAgo(5),
      createdAt: daysAgo(6),
      updatedAt: daysAgo(5),
    },
    // Quick Order pending delivery for Priya Sharma
    {
      id: 'ORD-Q-2002',
      orderType: 'QUICK',
      customerId: 'CUS-000002',
      customerName: 'Priya Sharma',
      customerMobile: '9835012345',
      deliveryAddress: 'House No 12, Harmu Housing Colony, Harmu, Ranchi - 834002',
      items: [
        {
          productId: 'PRD-004',
          productName: 'India Gate Basmati Rice Premium Feast Rozzana 1kg',
          brand: 'India Gate',
          weightSize: '1kg',
          barcode: '8901725114221',
          batchId: 'BATCH-005',
          batchNumber: 'RICE-99',
          manufacturingDate: daysAgo(90),
          expiryDate: daysFuture(400),
          quantity: 1,
          price: 118,
          mrp: 140,
          image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
        },
        {
          productId: 'PRD-006',
          productName: 'Tata Sampann Unpolished Toor Dal Arhar Dal 1kg',
          brand: 'Tata Sampann',
          weightSize: '1kg',
          barcode: '8901058852990',
          batchId: 'BATCH-007',
          batchNumber: 'DAL-44',
          manufacturingDate: daysAgo(30),
          expiryDate: daysFuture(330),
          quantity: 1,
          price: 172,
          mrp: 195,
          image: 'https://images.unsplash.com/photo-1585994276707-1b09b55589c3?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 290,
      deliveryFee: 30,
      totalAmount: 320,
      pantryDebitAmount: 0,
      codAmount: 320,
      paymentStatus: 'COD_PENDING',
      orderStatus: 'OUT_FOR_DELIVERY',
      assignedDeliveryBoyId: 'DEL-002',
      assignedDeliveryBoyName: 'Vikram Singh',
      assignedDeliveryBoyMobile: '9988776656',
      assignedAt: daysAgo(0),
      outForDeliveryAt: daysAgo(0),
      createdAt: daysAgo(1),
      updatedAt: daysAgo(0),
    },
  ];

  // Pantry Card Items: Customer physical stock with delivery dates
  const pantryCardItems: PantryCardItem[] = [
    // Ramesh Kumar (CUS-000001) - Delivered 9 days ago (9 Days Old, Return Eligible)
    {
      id: 'PCI-001',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      orderId: 'ORD-P-1001',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      brand: 'Horlicks',
      weightSize: '500g',
      barcode: '123456789',
      batchId: 'BATCH-001',
      batchNumber: '124001',
      manufacturingDate: daysAgo(60),
      expiryDate: daysFuture(300),
      image: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
      quantity: 1, // 1 remaining (1 was returned previously)
      unitPrice: 285,
      totalValue: 285,
      deliveryDate: daysAgo(9),
      status: 'RETURN_ELIGIBLE',
      auditorVerificationStatus: 'AVAILABLE',
      lastAuditorCheckDate: daysAgo(2),
      lastAuditorId: 'AUD-001',
      lastAuditorRemarks: 'Sealed jar verified in pantry shelf.',
      createdAt: daysAgo(9),
      updatedAt: daysAgo(2),
    },
    {
      id: 'PCI-002',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      orderId: 'ORD-P-1001',
      productId: 'PRD-002',
      productName: 'Aashirvaad Superior MP Shudh Chakki Atta 5kg',
      brand: 'Aashirvaad',
      weightSize: '5kg',
      barcode: '8901030382910',
      batchId: 'BATCH-003',
      batchNumber: 'ATT-801',
      manufacturingDate: daysAgo(25),
      expiryDate: daysFuture(155),
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      quantity: 1,
      unitPrice: 265,
      totalValue: 265,
      deliveryDate: daysAgo(9),
      status: 'RETURN_ELIGIBLE',
      auditorVerificationStatus: 'AVAILABLE',
      lastAuditorCheckDate: daysAgo(2),
      lastAuditorId: 'AUD-001',
      lastAuditorRemarks: 'Intact pack in kitchen pantry.',
      createdAt: daysAgo(9),
      updatedAt: daysAgo(2),
    },
    {
      id: 'PCI-003',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      orderId: 'ORD-P-1001',
      productId: 'PRD-003',
      productName: 'Fortune Sunlite Refined Sunflower Oil 1L Pouch',
      brand: 'Fortune',
      weightSize: '1L',
      barcode: '8906007281023',
      batchId: 'BATCH-004',
      batchNumber: 'OIL-502',
      manufacturingDate: daysAgo(40),
      expiryDate: daysFuture(200),
      image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
      quantity: 1,
      unitPrice: 152,
      totalValue: 152,
      deliveryDate: daysAgo(9),
      status: 'RETURN_ELIGIBLE',
      auditorVerificationStatus: 'AVAILABLE',
      lastAuditorCheckDate: daysAgo(2),
      lastAuditorId: 'AUD-001',
      createdAt: daysAgo(9),
      updatedAt: daysAgo(2),
    },
    // Sunita Kumar (CUS-000001-01) - Delivered 5 days ago (5 Days Old)
    {
      id: 'PCI-004',
      customerId: 'CUS-000001-01',
      customerName: 'Sunita Kumar',
      orderId: 'ORD-P-1002',
      productId: 'PRD-009',
      productName: 'Surf Excel Quick Wash Detergent Powder 1kg',
      brand: 'Surf Excel',
      weightSize: '1kg',
      barcode: '8901030704989',
      batchId: 'BATCH-010',
      batchNumber: 'SRF-201',
      manufacturingDate: daysAgo(40),
      expiryDate: daysFuture(500),
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
      quantity: 2,
      unitPrice: 145,
      totalValue: 290,
      deliveryDate: daysAgo(5),
      status: 'RETURN_ELIGIBLE',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
    {
      id: 'PCI-005',
      customerId: 'CUS-000001-01',
      customerName: 'Sunita Kumar',
      orderId: 'ORD-P-1002',
      productId: 'PRD-010',
      productName: 'Dettol Original Germ Protection Bathing Soap Bar (Pack of 4 x 125g)',
      brand: 'Dettol',
      weightSize: '500g',
      barcode: '8901396128001',
      batchId: 'BATCH-011',
      batchNumber: 'DET-909',
      manufacturingDate: daysAgo(50),
      expiryDate: daysFuture(600),
      image: 'https://images.unsplash.com/photo-1607006310414-b58602b9d628?auto=format&fit=crop&w=600&q=80',
      quantity: 1,
      unitPrice: 185,
      totalValue: 185,
      deliveryDate: daysAgo(5),
      status: 'RETURN_ELIGIBLE',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
    // Priya Sharma (CUS-000002) - Delivered 18 days ago (Past 15 days return window -> Replacement/Hold)
    {
      id: 'PCI-006',
      customerId: 'CUS-000002',
      customerName: 'Priya Sharma',
      orderId: 'ORD-P-900',
      productId: 'PRD-005',
      productName: 'Tata Salt Vacuum Evaporated Iodized Salt 1kg',
      brand: 'Tata',
      weightSize: '1kg',
      barcode: '8901058852303',
      batchId: 'BATCH-006',
      batchNumber: 'SLT-11',
      manufacturingDate: daysAgo(45),
      expiryDate: daysFuture(600),
      image: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=600&q=80',
      quantity: 2,
      unitPrice: 28,
      totalValue: 56,
      deliveryDate: daysAgo(18),
      status: 'DELIVERED',
      createdAt: daysAgo(18),
      updatedAt: daysAgo(18),
    },
    // Used / Consumed Pantry Items for Ramesh Kumar (0 Quantity)
    {
      id: 'PCI-007',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      orderId: 'ORD-P-1001',
      productId: 'PRD-004',
      productName: 'India Gate Basmati Rice Premium Feast Rozzana 1kg',
      brand: 'India Gate',
      weightSize: '1kg',
      barcode: '8901725114221',
      batchId: 'BATCH-005',
      batchNumber: 'RICE-99',
      manufacturingDate: daysAgo(90),
      expiryDate: daysFuture(400),
      image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
      quantity: 0, // Fully Used / Consumed in household
      unitPrice: 118,
      totalValue: 0,
      deliveryDate: daysAgo(20),
      status: 'DELIVERED',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(5),
    },
    {
      id: 'PCI-008',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      orderId: 'ORD-P-1001',
      productId: 'PRD-006',
      productName: 'Tata Sampann Unpolished Toor Dal Arhar Dal 1kg',
      brand: 'Tata Sampann',
      weightSize: '1kg',
      barcode: '8901058852990',
      batchId: 'BATCH-007',
      batchNumber: 'DAL-44',
      manufacturingDate: daysAgo(40),
      expiryDate: daysFuture(330),
      image: 'https://images.unsplash.com/photo-1585994276707-1b09b55589c3?auto=format&fit=crop&w=600&q=80',
      quantity: 0, // Fully Used / Consumed in household
      unitPrice: 172,
      totalValue: 0,
      deliveryDate: daysAgo(20),
      status: 'DELIVERED',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(3),
    },
  ];

  // Pantry Credit Ledgers
  const pantryCreditLedger: PantryCreditLedger[] = [
    {
      id: 'PCL-001',
      customerId: 'CUS-000001',
      transactionType: 'INITIAL_LIMIT',
      openingLimit: 0,
      amount: 10000,
      closingLimit: 10000,
      description: 'Standard initial pantry limit granted',
      createdAt: daysAgo(20),
    },
    {
      id: 'PCL-002',
      customerId: 'CUS-000001',
      transactionType: 'PANTRY_ORDER_DEBIT',
      openingLimit: 10000,
      amount: -987,
      closingLimit: 9013,
      referenceId: 'ORD-P-1001',
      description: 'Pantry order placement ORD-P-1001 debit',
      createdAt: daysAgo(10),
    },
    {
      id: 'PCL-003',
      customerId: 'CUS-000001',
      transactionType: 'RETURN_CREDIT',
      openingLimit: 9013,
      amount: 285,
      closingLimit: 9298,
      referenceId: 'RET-001',
      description: 'Returned 1 unit Horlicks 500g (Batch 124001) credit refund',
      createdAt: daysAgo(4),
    },
    {
      id: 'PCL-004',
      customerId: 'CUS-000001',
      transactionType: 'PANTRY_ORDER_DEBIT',
      openingLimit: 9298,
      amount: -1748,
      closingLimit: 7550,
      referenceId: 'ORD-P-1003',
      description: 'Pantry groceries refill order ORD-P-1003 debit',
      createdAt: daysAgo(3),
    },
    {
      id: 'PCL-005',
      customerId: 'CUS-000001-01',
      transactionType: 'INITIAL_LIMIT',
      openingLimit: 0,
      amount: 5000,
      closingLimit: 5000,
      description: 'Child customer allocated pantry limit',
      createdAt: daysAgo(15),
    },
    {
      id: 'PCL-006',
      customerId: 'CUS-000001-01',
      transactionType: 'PANTRY_ORDER_DEBIT',
      openingLimit: 5000,
      amount: -475,
      closingLimit: 4525,
      referenceId: 'ORD-P-1002',
      description: 'Pantry order ORD-P-1002 debit',
      createdAt: daysAgo(6),
    },
  ];

  // Customer Wallet Transactions (Dedicated Customer Wallet Ledger)
  const walletTransactions: WalletTransaction[] = [
    {
      id: 'WLT-000001',
      customerId: 'CUS-000001',
      transactionType: 'OPENING_BALANCE',
      amount: 1000,
      previousBalance: 0,
      newBalance: 1000,
      referenceId: 'SYS-INIT',
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      date: daysAgo(20),
      time: '10:00 AM',
      timestamp: `${daysAgo(20)} 10:00:00`,
      reason: 'Initial system default wallet credit',
      status: 'SUCCESS',
    },
    {
      id: 'WLT-000002',
      customerId: 'CUS-000001-01',
      transactionType: 'OPENING_BALANCE',
      amount: 1000,
      previousBalance: 0,
      newBalance: 1000,
      referenceId: 'SYS-INIT',
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      date: daysAgo(15),
      time: '11:00 AM',
      timestamp: `${daysAgo(15)} 11:00:00`,
      reason: 'Initial system default wallet credit',
      status: 'SUCCESS',
    },
    {
      id: 'WLT-000003',
      customerId: 'CUS-000001-02',
      transactionType: 'OPENING_BALANCE',
      amount: 1000,
      previousBalance: 0,
      newBalance: 1000,
      referenceId: 'SYS-INIT',
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      date: daysAgo(10),
      time: '09:30 AM',
      timestamp: `${daysAgo(10)} 09:30:00`,
      reason: 'Initial system default wallet credit',
      status: 'SUCCESS',
    },
    {
      id: 'WLT-000004',
      customerId: 'CUS-000002',
      transactionType: 'OPENING_BALANCE',
      amount: 1000,
      previousBalance: 0,
      newBalance: 1000,
      referenceId: 'SYS-INIT',
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      date: daysAgo(10),
      time: '10:00 AM',
      timestamp: `${daysAgo(10)} 10:00:00`,
      reason: 'Initial system default wallet credit',
      status: 'SUCCESS',
    },
    {
      id: 'WLT-000005',
      customerId: 'CUS-000002',
      transactionType: 'ADMIN_RECHARGE',
      amount: 1000,
      previousBalance: 1000,
      newBalance: 2000,
      referenceId: 'RCG-88219',
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      date: daysAgo(3),
      time: '02:30 PM',
      timestamp: `${daysAgo(3)} 14:30:00`,
      reason: 'Admin top-up for premium customer security deposit',
      status: 'SUCCESS',
    },
    {
      id: 'WLT-000006',
      customerId: 'CUS-000003',
      transactionType: 'OPENING_BALANCE',
      amount: 1000,
      previousBalance: 0,
      newBalance: 1000,
      referenceId: 'SYS-INIT',
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      date: daysAgo(5),
      time: '12:00 PM',
      timestamp: `${daysAgo(5)} 12:00:00`,
      reason: 'Initial system default wallet credit',
      status: 'SUCCESS',
    },
  ];

  // Return Requests
  const returnRequests: ReturnRequest[] = [
    {
      id: 'RET-001',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      orderId: 'ORD-P-1001',
      pantryCardItemId: 'PCI-001',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      barcode: '123456789',
      batchId: 'BATCH-001',
      batchNumber: '124001',
      quantity: 1,
      refundCreditAmount: 285,
      reason: 'Extra quantity ordered by mistake, outer seal untouched',
      status: 'COMPLETED',
      initiatedBy: 'CUSTOMER',
      initiatedById: 'CUS-000001',
      assignedDeliveryBoyId: 'DEL-001',
      processedAt: daysAgo(4),
      createdAt: daysAgo(5),
    },
  ];

  // Replacement Requests
  const replacementRequests: ReplacementRequest[] = [
    {
      id: 'REP-001',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      orderId: 'ORD-P-1001',
      originalPantryCardItemId: 'PCI-002',
      productId: 'PRD-002',
      productName: 'Aashirvaad Superior MP Shudh Chakki Atta 5kg',
      barcode: '8901030382910',
      originalBatchId: 'BATCH-003',
      originalBatchNumber: 'ATT-801',
      replacementBatchId: 'BATCH-003',
      replacementBatchNumber: 'ATT-801',
      quantity: 1,
      reason: 'Packaging bag slightly punctured during transit',
      status: 'PENDING',
      initiatedBy: 'AUDITOR',
      initiatedById: 'AUD-001',
      createdAt: daysAgo(2),
    },
  ];

  // Auditor Checks
  const auditorChecks: AuditorCheck[] = [
    {
      id: 'AUD-CHK-001',
      auditRequestId: 'AUD-REQ-001',
      billId: 'BILL-AUD-000101',
      billStatus: 'LOCKED',
      isBillLocked: true,
      billVersion: 1,
      auditorId: 'AUD-001',
      auditorName: 'Suresh Field Auditor',
      customerId: 'CUS-000001',
      customerName: 'Ramesh Kumar',
      customerAddress: 'Flat 402, Shanti Vihar, Circular Road, Lalpur, Ranchi',
      customerMobile: '9123456780',
      status: 'LOCKED',
      purpose: 'Routine Monthly Pantry Inventory Physical Verification',
      requestedDate: daysAgo(3),
      requestedTime: '11:00 AM',
      requestedAt: `${daysAgo(3)} 09:30:00`,
      customerConfirmedAt: `${daysAgo(3)} 10:15:00`,
      customerConfirmedDate: daysAgo(3),
      customerConfirmedTime: '10:15 AM',
      visitDate: daysAgo(2),
      visitTime: '11:30 AM',
      startedAt: `${daysAgo(2)} 11:30:00`,
      completedAt: `${daysAgo(2)} 11:54:30`,
      durationMinutes: 24,
      durationFormatted: '24 mins 30 secs',
      reportGeneratedAt: `${daysAgo(2)} 11:55:00`,
      billGeneratedAt: `${daysAgo(2)} 11:55:00`,
      billGeneratedDate: daysAgo(2),
      billGeneratedTime: '11:55 AM',
      billConfirmedAt: `${daysAgo(2)} 12:10:00`,
      billConfirmedDate: daysAgo(2),
      billConfirmedTime: '12:10 PM',
      billConfirmedBy: 'Ramesh Kumar (Household)',
      billLockedAt: `${daysAgo(2)} 12:10:00`,
      billLockedDate: daysAgo(2),
      billLockedTime: '12:10 PM',
      itemsChecked: [
        {
          pantryCardItemId: 'PCI-001',
          productId: 'PRD-001',
          productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
          productPrice: 285,
          batchNumber: '124001',
          manufacturingDate: daysAgo(60),
          expiryDate: daysFuture(300),
          quantity: 1,
          qtyAvailable: 1,
          qtyMissing: 0,
          qtyDamaged: 0,
          qtyPantryPay: 0,
          deliveryDate: daysAgo(9),
          daysSinceDelivery: 7,
          verificationStatus: 'AVAILABLE',
          actionTaken: 'NONE',
          remarks: 'Verified sealed pack in stock.',
          images: [
            'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
          ],
        },
        {
          pantryCardItemId: 'PCI-002',
          productId: 'PRD-002',
          productName: 'Aashirvaad Superior MP Shudh Chakki Atta 5kg',
          productPrice: 245,
          batchNumber: 'ATT-801',
          manufacturingDate: daysAgo(25),
          expiryDate: daysFuture(155),
          quantity: 1,
          qtyAvailable: 0,
          qtyMissing: 0,
          qtyDamaged: 1,
          qtyPantryPay: 0,
          deliveryDate: daysAgo(9),
          daysSinceDelivery: 7,
          verificationStatus: 'DAMAGED',
          actionTaken: 'REPLACEMENT_INITIATED',
          remarks: 'Punctured outer seal - initiated replacement.',
          images: [
            'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=600&q=80',
          ],
        },
        {
          pantryCardItemId: 'PCI-003',
          productId: 'PRD-003',
          productName: 'Fortune Sunlite Refined Sunflower Oil 1L Pouch',
          productPrice: 145,
          batchNumber: 'OIL-502',
          manufacturingDate: daysAgo(40),
          expiryDate: daysFuture(200),
          quantity: 1,
          qtyAvailable: 1,
          qtyMissing: 0,
          qtyDamaged: 0,
          qtyPantryPay: 0,
          deliveryDate: daysAgo(9),
          daysSinceDelivery: 7,
          verificationStatus: 'AVAILABLE',
          actionTaken: 'NONE',
          remarks: 'Available and safe.',
          images: [
            'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
            'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?auto=format&fit=crop&w=600&q=80',
          ],
        },
      ],
      totalItemsCount: 3,
      availableCount: 2,
      notAvailableCount: 0,
      damagedCount: 1,
      expiredCount: 0,
      nearExpiryCount: 0,
      returnsInitiatedCount: 0,
      replacementsInitiatedCount: 1,
      walletBefore: 1000,
      totalWalletDeduction: 0,
      walletAfter: 1000,
      isBillConfirmed: true,
      overallRemarks: 'Pantry verification completed smoothly at customer residence. 1 replacement flagged.',
      auditorSignatureStatus: true,
      customerSignatureStatus: true,
      createdAt: `${daysAgo(3)} 09:30:00`,
    },
    {
      id: 'AUD-CHK-002',
      auditRequestId: 'AUD-REQ-002',
      billId: 'BILL-AUD-000102',
      billStatus: 'CUSTOMER_PENDING_CONFIRMATION',
      isBillLocked: false,
      billVersion: 1,
      auditorId: 'AUD-001',
      auditorName: 'Suresh Field Auditor',
      customerId: 'CUS-000002',
      customerName: 'Priya Sharma',
      customerAddress: 'House 12B, Bariatu Road, Near Medical College, Ranchi',
      customerMobile: '9123456781',
      status: 'CUSTOMER_PENDING_CONFIRMATION',
      purpose: 'Bi-Weekly Household Audit & Consumption Check',
      requestedDate: daysAgo(1),
      requestedTime: '03:30 PM',
      requestedAt: `${daysAgo(1)} 14:00:00`,
      customerConfirmedAt: `${daysAgo(1)} 14:30:00`,
      customerConfirmedDate: daysAgo(1),
      customerConfirmedTime: '02:30 PM',
      visitDate: daysAgo(1),
      visitTime: '03:45 PM',
      startedAt: `${daysAgo(1)} 03:45:00`,
      completedAt: `${daysAgo(1)} 04:12:00`,
      durationMinutes: 27,
      durationFormatted: '27 mins',
      reportGeneratedAt: `${daysAgo(1)} 04:15:00`,
      billGeneratedAt: `${daysAgo(1)} 04:15:00`,
      billGeneratedDate: daysAgo(1),
      billGeneratedTime: '04:15 PM',
      itemsChecked: [
        {
          pantryCardItemId: 'PCI-004',
          productId: 'PRD-004',
          productName: 'Tata Salt Vacuum Evaporated 1kg',
          productPrice: 28,
          batchNumber: 'SLT-101',
          manufacturingDate: daysAgo(30),
          expiryDate: daysFuture(365),
          quantity: 2,
          qtyAvailable: 2,
          qtyMissing: 0,
          qtyDamaged: 0,
          qtyPantryPay: 0,
          deliveryDate: daysAgo(12),
          daysSinceDelivery: 10,
          verificationStatus: 'AVAILABLE',
          actionTaken: 'NONE',
          remarks: 'Both sealed packets verified.',
          images: ['https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=600&q=80'],
        },
      ],
      totalItemsCount: 2,
      availableCount: 2,
      notAvailableCount: 0,
      damagedCount: 0,
      expiredCount: 0,
      nearExpiryCount: 0,
      returnsInitiatedCount: 0,
      replacementsInitiatedCount: 0,
      walletBefore: 1500,
      totalWalletDeduction: 0,
      walletAfter: 1500,
      isBillConfirmed: false,
      overallRemarks: 'All pantry provisions accounted for in good condition.',
      auditorSignatureStatus: true,
      customerSignatureStatus: false,
      createdAt: `${daysAgo(1)} 14:00:00`,
    },
  ];

  // Inventory Transactions Ledger
  const inventoryTransactions: InventoryTransaction[] = [
    {
      id: 'TXN-001',
      dateTime: `${daysAgo(30)} 10:00:00`,
      movementType: 'PURCHASE',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      batchId: 'BATCH-001',
      batchNumber: '124001',
      quantity: 5,
      previousStock: 0,
      movementQuantity: 5,
      newStock: 5,
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      reason: 'Purchase Inward from Ranchi Wholesale FMCG Mart',
      reference: 'PUR-001',
    },
    {
      id: 'TXN-002',
      dateTime: `${daysAgo(28)} 14:15:00`,
      movementType: 'PURCHASE',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      batchId: 'BATCH-001',
      batchNumber: '124001',
      quantity: 3,
      previousStock: 5,
      movementQuantity: 3,
      newStock: 8,
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      reason: 'Same Batch Repeat Purchase Inward (+3 Qty)',
      reference: 'PUR-002',
    },
    {
      id: 'TXN-003',
      dateTime: `${daysAgo(10)} 16:30:00`,
      movementType: 'PANTRY_SALE',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      batchId: 'BATCH-001',
      batchNumber: '124001',
      quantity: 2,
      previousStock: 8,
      movementQuantity: -2,
      newStock: 6,
      orderId: 'ORD-P-1001',
      customerId: 'CUS-000001',
      userId: 'USR-CUS-01',
      role: 'CUSTOMER',
      reason: 'Pantry order fulfillment',
    },
    {
      id: 'TXN-004',
      dateTime: `${daysAgo(4)} 11:20:00`,
      movementType: 'RETURN',
      productId: 'PRD-001',
      productName: 'Horlicks Health & Nutrition Drink Classic Malt 500g',
      batchId: 'BATCH-001',
      batchNumber: '124001',
      quantity: 1,
      previousStock: 5,
      movementQuantity: 1,
      newStock: 6,
      customerId: 'CUS-000001',
      userId: 'USR-ADMIN-01',
      role: 'ADMIN',
      reason: 'Valid Customer Return of Batch 124001',
      reference: 'RET-001',
    },
  ];

  // Audit Logs
  const auditLogs: AuditLog[] = [
    {
      id: 'LOG-001',
      who: 'System Administrator',
      role: 'ADMIN',
      action: 'INITIALIZE_SYSTEM',
      entity: 'SYSTEM',
      entityId: 'SYS',
      newValue: 'Bootstrapped multi-role Grocery & Pantry logistics database',
      timestamp: `${daysAgo(30)} 09:00:00`,
    },
    {
      id: 'LOG-002',
      who: 'System Administrator',
      role: 'ADMIN',
      action: 'CREATE_PURCHASE',
      entity: 'PURCHASE',
      entityId: 'PUR-001',
      newValue: 'Added 5 units Horlicks (Batch 124001) from Ranchi Wholesale FMCG Mart',
      timestamp: `${daysAgo(30)} 10:00:00`,
    },
    {
      id: 'LOG-003',
      who: 'System Administrator',
      role: 'ADMIN',
      action: 'STOCK_ADDITION_SAME_BATCH',
      entity: 'BATCH',
      entityId: 'BATCH-001',
      oldValue: '5',
      newValue: '8',
      reason: 'Purchased 3 more units of existing Batch 124001',
      timestamp: `${daysAgo(28)} 14:15:00`,
    },
    {
      id: 'LOG-004',
      who: 'Ramesh Kumar',
      role: 'CUSTOMER',
      action: 'CREATE_PANTRY_ORDER',
      entity: 'ORDER',
      entityId: 'ORD-P-1001',
      newValue: 'Placed Pantry Order ₹987 (Debited Pantry Credit)',
      timestamp: `${daysAgo(10)} 16:30:00`,
    },
    {
      id: 'LOG-005',
      who: 'Suresh Field Auditor',
      role: 'AUDITOR',
      action: 'VERIFY_PANTRY_CARD',
      entity: 'AUDITOR_CHECK',
      entityId: 'AUD-CHK-001',
      newValue: 'Physical verification for customer CUS-000001 completed (3 items checked)',
      timestamp: `${daysAgo(2)} 11:45:00`,
    },
  ];

  return {
    users,
    customers,
    deliveryBoys,
    auditors,
    products,
    batches,
    purchases,
    orders,
    pantryCardItems,
    pantryCreditLedger,
    walletTransactions,
    returnRequests,
    replacementRequests,
    auditorChecks,
    inventoryTransactions,
    auditLogs,
    pantryPayments: [],
    walletRechargeRequests: [],
    auditorReturnOrders: [],
    settings: defaultSettings,
  };
};

class DatabaseStore {
  private db: DatabaseSchema | null = null;
  private isWriting = false;

  constructor() {
    this.init();
  }

  private init() {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }

      if (fs.existsSync(DB_FILE)) {
        const raw = fs.readFileSync(DB_FILE, 'utf-8');
        this.db = JSON.parse(raw);
        this.migrateDb();
      } else {
        this.db = getInitialSeeds();
        this.saveSync();
      }
    } catch (e) {
      console.error('Error loading database file, initializing seeds:', e);
      this.db = getInitialSeeds();
      this.saveSync();
    }
  }

  private migrateDb() {
    if (!this.db) return;
    let modified = false;

    if (!this.db.walletTransactions) {
      this.db.walletTransactions = [];
      modified = true;
    }

    if (!this.db.walletRechargeRequests) {
      this.db.walletRechargeRequests = [];
      modified = true;
    }

    if (!this.db.pantryPayments) {
      this.db.pantryPayments = [];
      modified = true;
    }

    if (!this.db.auditorReturnOrders) {
      this.db.auditorReturnOrders = [];
      modified = true;
    }

    if (this.db.customers) {
      for (const c of this.db.customers) {
        if (c.walletBalance === undefined || isNaN(c.walletBalance)) {
          c.walletBalance = 1000;
          modified = true;
        }
      }
    }

    if (this.db.settings) {
      if (this.db.settings.defaultWalletBalance === undefined) {
        this.db.settings.defaultWalletBalance = 1000;
        modified = true;
      }
      if (this.db.settings.walletRechargeEnabled === undefined) {
        this.db.settings.walletRechargeEnabled = true;
        modified = true;
      }
      if (this.db.settings.auditWalletDeductionEnabled === undefined) {
        this.db.settings.auditWalletDeductionEnabled = true;
        modified = true;
      }
      if (this.db.settings.allowNegativeWallet === undefined) {
        this.db.settings.allowNegativeWallet = false;
        modified = true;
      }
      if (this.db.settings.auditRequireCustomerConfirmation === undefined) {
        this.db.settings.auditRequireCustomerConfirmation = true;
        modified = true;
      }
      if (this.db.settings.pantryOrderCodEnabled === undefined) {
        this.db.settings.pantryOrderCodEnabled = false;
        modified = true;
      }
      if (!this.db.settings.apiIntegrations) {
        this.db.settings.apiIntegrations = (getInitialSeeds().settings as any).apiIntegrations;
        modified = true;
      }
      if (this.db.settings.apiIntegrations && !this.db.settings.apiIntegrations.supabase) {
        this.db.settings.apiIntegrations.supabase = {
          mode: 'LIVE',
          provider: 'SUPABASE',
          enabled: true,
          url: DEFAULT_SUPABASE_URL,
          anonKey: DEFAULT_SUPABASE_ANON_KEY,
          serviceRoleKey: DEFAULT_SUPABASE_SERVICE_ROLE_KEY,
          projectRef: DEFAULT_PROJECT_REF,
          dbUrl: DEFAULT_DB_URL,
          autoSync: true,
          lastTestedAt: new Date().toISOString(),
          lastTestStatus: 'SUCCESS',
          lastTestMessage: 'Supabase Cloud Database (bgxnmmecjcgrwtemmjtz) connected',
          connected: true,
        };
        modified = true;
      } else if (this.db.settings.apiIntegrations?.supabase) {
        if (!this.db.settings.apiIntegrations.supabase.serviceRoleKey) {
          this.db.settings.apiIntegrations.supabase.serviceRoleKey = DEFAULT_SUPABASE_SERVICE_ROLE_KEY;
          modified = true;
        }
      }
    }

    if (modified) {
      this.saveSync();
    }
  }

  private saveSync() {
    if (!this.db) return;
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      const tmpFile = `${DB_FILE}.tmp`;
      fs.writeFileSync(tmpFile, JSON.stringify(this.db, null, 2), 'utf-8');
      fs.renameSync(tmpFile, DB_FILE);

      // Real-time synchronization to Supabase Cloud Database on every entry & update
      if (this.db) {
        supabaseService.syncPush(this.db).catch((e) => {
          console.warn('[Supabase Real-Time Sync] Background push warning:', e?.message || e);
        });
      }
    } catch (err) {
      console.error('Failed to write database file:', err);
    }
  }

  public getDb(): DatabaseSchema {
    if (!this.db) {
      this.init();
    }
    return this.db!;
  }

  public save() {
    this.saveSync();
    this.syncToSupabase().catch((err: any) => console.warn('[Auto-Sync Supabase Error]:', err.message));
  }

  public async syncToSupabase() {
    if (!this.db) this.getDb();
    return await supabaseService.syncPush(this.db);
  }

  public async loadFromSupabase(): Promise<boolean> {
    const res = await supabaseService.syncPull();
    if (res.success && res.data) {
      this.db = res.data;
      this.saveSync();
      return true;
    }
    return false;
  }

  public resetToSeeds(): DatabaseSchema {
    this.db = getInitialSeeds();
    this.saveSync();
    return this.db;
  }
}

export const store = new DatabaseStore();
